version: "2"
services:
    app:
        build: ./app
        ports:
            - 5000:5000
        volumes:
            - ./app:/app
        links:
            - db
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: dariussarbu
            MYSQL_DATABASE: containermanager
            MYSQL_USER: darius
            MYSQL_PASSWORD: dariussarbu

